
name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Backend Build & Test
        run: |
          cd backend
          npm install
          npm test
      - name: Frontend Build & Test
        run: |
          cd frontend
          npm install
          npm test

